http -f post treatyoself.herokuapp.com url='http://pesatalk.com/wp-content/uploads/2012/07/Insanely-expensive-stuff.png'
http -f post treatyoself.herokuapp.com url='http://basel.watchprosite.com/img/watchprosite/ml/51/scaled/ml_image.976651.jpg'
http -f post treatyoself.herokuapp.com url='http://www.decodedstuff.com/wp-content/uploads/2010/05/most-expensive-hello-kitty-statue.jpg'
http -f post treatyoself.herokuapp.com url='http://www.polyvore.com/cgi/img-thing?.out=jpg&size=l&tid=39455743'
http -f post treatyoself.herokuapp.com url='http://nakur.files.wordpress.com/2007/06/dinoreplica1.jpg?w=490'
http -f post treatyoself.herokuapp.com url='http://almostnothingbutmusic.files.wordpress.com/2013/02/gold-bling_turntable_buckle.jpg'
http -f post treatyoself.herokuapp.com url='http://new-cdn.financialsamurai.com.s3.amazonaws.com/wp-content/uploads/2011/06/puppystroller-224x300.jpg'
http -f post treatyoself.herokuapp.com url='http://img.photobucket.com/albums/v284/xzaznricezx/Prodigy/2013-01-23190456_zps03500ecc.jpg'