http -f post treatyoself.herokuapp.com url='http://blog.zap2it.com/frominsidethebox/parks-and-rec-treat-yoursel.jpg'
http -f post treatyoself.herokuapp.com url='http://oi52.tinypic.com/afihkh.jpg'
http -f post treatyoself.herokuapp.com url='http://24.media.tumblr.com/tumblr_m8mtpz78vu1rs7wu4o1_r2_500.jpg'
http -f post treatyoself.herokuapp.com url='http://michiganjournal.org/wp-content/uploads/2012/11/parks-and-rec-treat-yo-self.gif'
http -f post treatyoself.herokuapp.com url='http://sherryndaniel.files.wordpress.com/2012/02/treat-to-self-2.jpg'
http -f post treatyoself.herokuapp.com url='http://media.tumblr.com/tumblr_m8u0ziwt5i1rqpx0x.gif'
http -f post treatyoself.herokuapp.com url='http://www.newdressaday.com/wp-content/uploads/2011/11/photo7.jpg'
http -f post treatyoself.herokuapp.com url='http://25.media.tumblr.com/tumblr_lt2w75rKZO1qazkdco1_500.gif'